**Simplest SLP**


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Define the model
model = Sequential([
    Dense(1, input_shape=(1,), activation='sigmoid')  # Single neuron with sigmoid activation
])

# Compile the model 
model.compile(optimizer='sgd', loss='binary_crossentropy',
              metrics=['accuracy'])

np.random.seed(0)
X = np.random.rand(100).reshape(-1, 1)  # Shape for input layer
y = np.array([1 if x >= 0.5 else 0 for x in X])  # Label: <0.5 => 0, >=0.5 => 1

# Train the model without epoch output
model.fit(X, y, epochs=10, verbose=0)

# Function to get user input and classify it
def user_input_classification():
    user_input = float(input("Enter a number between 0 and 1: "))  # Expecting valid float input
    if 0 <= user_input <= 1:
        prediction = model.predict(np.array([user_input]))  # Predict with the trained model
        classification = 1 if prediction > 0.5 else 0
        print(f"Perceptron classification: {classification}")
    else:
        print("Please enter a number between 0 and 1.")

# Classify user input
user_input_classification()



**Code with two input neurons**

In [6]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Define the model with two input neurons
model = Sequential([
    Dense(1, input_shape=(2,), activation='sigmoid')
])

# Compile the model
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

# Generate random training data with two features
np.random.seed(0)
X = np.random.rand(100, 2)  # Each row now has two values
y = np.array([1 if x[0] >= 0.5 and  x[1] >= 0.5 else 0 for x in X])  # Label based on sum of features

# Train the model with more epochs for accuracy
model.fit(X, y, epochs=500, verbose=0)  # Increased epochs

# Function to get user input and classify it
def user_input_classification():
    # Collect two user inputs
    user_input1 = float(input("Enter first number between 0 and 1: "))
    user_input2 = float(input("Enter second number between 0 and 1: "))

    # Clamp each input to the range [0, 1]
    #user_input1 = max(0, min(user_input1, 1))
    #user_input2 = max(0, min(user_input2, 1))

    # Reshape inputs for prediction
    user_inputs = np.array([[user_input1, user_input2]])

    # Predict and classify
    prediction = model.predict(user_inputs)
    classification = int(prediction[0][0] >= 0.5)  # Threshold at 0.5
    print(f"Perceptron classification: {classification}")

# Classify user input
user_input_classification()

Enter first number between 0 and 1: 0.5
Enter second number between 0 and 1: 0.4
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
Perceptron classification: 0


**Code with additional hidden layer and two input neurons**

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Define the model with a hidden layer of two neurons and an output layer
model = Sequential([
    Dense(2, input_shape=(2,), activation='sigmoid'),   # Hidden layer with 2 neurons and ReLU activation
    Dense(1, activation='sigmoid')                   # Output layer with 1 neuron and sigmoid activation
])

# Compile the model
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

# Generate random training data with two features
np.random.seed(0)
X = np.random.rand(100, 2)  # Each row now has two values
y = np.array([1 if x[0] + x[1] >= 1 else 0 for x in X])  # Label based on sum of features

# Train the model with more epochs for accuracy
model.fit(X, y, epochs=500, verbose=0)  # Increased epochs

# Function to get user input and classify it
def user_input_classification():
    # Collect two user inputs
    user_input1 = float(input("Enter first number between 0 and 1: "))
    user_input2 = float(input("Enter second number between 0 and 1: "))

    # Clamp each input to the range [0, 1]
    user_input1 = max(0, min(user_input1, 1))
    user_input2 = max(0, min(user_input2, 1))

    # Reshape inputs for prediction
    user_inputs = np.array([[user_input1, user_input2]])

    # Predict and classify
    prediction = model.predict(user_inputs)
    classification = int(prediction[0][0] >= 0.5)  # Threshold at 0.5
    print(f"Perceptron classification: {classification}")

# Classify user input
user_input_classification()


**Linear Regression**

In [ ]:
# Import necessary libraries
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import tensorflow as tf

# Sample data: X (input), Y (output) for training
# Example: Let's assume we're predicting the output of a linear equation y = 2x + 1
X = np.array([1, 2, 3, 4, 5], dtype=float)
Y = np.array([3, 5, 7, 9, 11], dtype=float)

# Build the ANN model
model = Sequential([
    Dense(units=1, input_shape=(1,), activation='linear')
    ])

# Compile the model with SGD optimizer
model.compile(optimizer='sgd', loss='mean_squared_error')

# Train the model without displaying the epochs
model.fit(X, Y, epochs=1000, verbose=0)

# Predict the output for a user input
user_input = float(input("Enter a value for prediction: "))
prediction = model.predict(np.array([[user_input]]))

# Display the prediction
print(f"Predicted output for input {user_input}: {prediction[0][0]}")


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Enter a value for prediction: 6
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
Predicted output for input 6.0: 13.009330749511719


In [92]:
X = np.random.rand(10,2)
X

array([[0.52775714, 0.9460802 ],
       [0.32624897, 0.84459279],
       [0.2654785 , 0.96214005],
       [0.66825226, 0.47532581],
       [0.16353675, 0.91633457],
       [0.89164228, 0.96208198],
       [0.00999623, 0.4286716 ],
       [0.72974264, 0.66967343],
       [0.18495765, 0.61770311],
       [0.65782998, 0.68907958]])

In [110]:
np.random.seed(0)
X = np.random.rand(10,2) # row,column
print(X)


[[0.5488135  0.71518937]
 [0.60276338 0.54488318]
 [0.4236548  0.64589411]
 [0.43758721 0.891773  ]
 [0.96366276 0.38344152]
 [0.79172504 0.52889492]
 [0.56804456 0.92559664]
 [0.07103606 0.0871293 ]
 [0.0202184  0.83261985]
 [0.77815675 0.87001215]]


In [106]:
y = np.array[1 if X[0]>=0.5 and X[1] >= 5 else 0 for x in X]
print(y)

y = np.array([1 if x[0] >= 0.5 and  x[1] >= 0.5 else 0 for x in X])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [125]:
for x in X:
    print(x[0], x[1])

0.5488135039273248 0.7151893663724195
0.6027633760716439 0.5448831829968969
0.4236547993389047 0.6458941130666561
0.4375872112626925 0.8917730007820798
0.9636627605010293 0.3834415188257777
0.7917250380826646 0.5288949197529045
0.5680445610939323 0.925596638292661
0.07103605819788694 0.08712929970154071
0.02021839744032572 0.832619845547938
0.7781567509498505 0.8700121482468192


In [127]:
for x in X:
    if x[0]>=0.5 and x[1]>=0.5: #0.5488135039273248 0.7151893663724195
        print(1)
    else:
        print(0)

1
1
0
0
0
1
1
0
0
1


In [30]:
import numpy as np
a = 5
b = np.array([a])
print(b)
print(type(b))
b.ndim

[5]
<class 'numpy.ndarray'>


1

In [32]:
b = np.array(a)
print(b)
print(type(b))
b.ndim

5
<class 'numpy.ndarray'>


0

In [34]:
# important

# [user_input] -> 1d
# np.array([user_input]) -> 1d array

# model.prediction(np.array([user_input]))

In [38]:
# code with 2 input nodes/neurons

a = int(input("enter a number"))
b = int(input("enter a number"))
c = np.array([[a,b]])
print(c)
print(type(c))

enter a number 1
enter a number 2


[[1 2]]
<class 'numpy.ndarray'>


In [1]:
print(c[0][0])  #  0th row, 0th col
print(c[0][1])

NameError: name 'c' is not defined